version: "3.6"

services:  
  traefik:
    image: "janeiro/test-app:dev"
    container_name: "app"
    networks:
      - app
      - devstack

networks:
  app:
    external: false
    name: janeiro-test-app
  
  devstack:
    external: true
    name: devstack
