version: "3.6"

services:  
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - devstack
  
  jaeger:
    image: jaegertracing/all-in-one:1.57.0
    ports:
      - 16686:16686
      - 4318:4318
    networks:
      - devstack

networks:
  devstack:
    external: false
    name: devstack
